GMAIL_USERNAME: 'ducbk95@gmail.com'
GMAIL_PASSWORD: '02091995'

aws_access_key_id: 'AKIAJPIXOD4NTIVKWGUQ'
aws_secret_access_key: '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'
associate_tag: 'venshop05-20'

api_key: '126339711758862'
api_secret: '3goOcTtZXUQvZQhEgj8g-hzlOds'
cloud_name: 'dcmwhmyzp'
