Category.create(name: "Electronics", keyword: 'Laptop')
Category.create(name: "Software", keyword: "New")
Category.create(name: "Appliances", keyword: "Refrigerator")
Category.create(name: "Apparel", keyword: "Men")
Category.create(name: "Books", keyword: "Books")
#Category.create(name: "Electronics", keyword: "Computer")
